//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFAWaldos.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hd_codigosqr
    {
        public int id { get; set; }
        public string codigo { get; set; }
        public int hd_ordenes_id { get; set; }
    
        public virtual hd_ordenes hd_ordenes { get; set; }
    }
}
