//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFAWaldos.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hd_ordenes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hd_ordenes()
        {
            this.hd_codigosqr = new HashSet<hd_codigosqr>();
        }
    
        public int id { get; set; }
        public string orden { get; set; }
        public string oracleid { get; set; }
        public Nullable<System.DateTime> fechacreacion { get; set; }
        public Nullable<System.DateTime> fechacierre { get; set; }
        public Nullable<int> paquetes { get; set; }
        public string observaciones { get; set; }
        public int Pickers_Id { get; set; }
        public int Auditores_Id { get; set; }
        public int hd_statusquickship_id { get; set; }
        public int hd_statusorden_id { get; set; }
        public int hd_guias_id { get; set; }
    
        public virtual auditores auditores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hd_codigosqr> hd_codigosqr { get; set; }
        public virtual hd_guias hd_guias { get; set; }
        public virtual hd_statusorden hd_statusorden { get; set; }
        public virtual hd_statusquickship hd_statusquickship { get; set; }
        public virtual pickers pickers { get; set; }
    }
}
