//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFAWaldos.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class kitskus
    {
        public int id { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public int kits_Id { get; set; }
        public int skus_Id { get; set; }
    
        public virtual kits kits { get; set; }
        public virtual skus skus { get; set; }
    }
}
