//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFAWaldos.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_A3F19C_producccionEntities : DbContext
    {
        public DB_A3F19C_producccionEntities()
            : base("name=DB_A3F19C_producccionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<wl_detcajassku> wl_detcajassku { get; set; }
        public virtual DbSet<wl_detenvios> wl_detenvios { get; set; }
        public virtual DbSet<wl_guias> wl_guias { get; set; }
        public virtual DbSet<wl_statuscajas> wl_statuscajas { get; set; }
        public virtual DbSet<wl_tiendas> wl_tiendas { get; set; }
        public virtual DbSet<wl_waldos> wl_waldos { get; set; }
        public virtual DbSet<skus> skus { get; set; }
        public virtual DbSet<auditores> auditores { get; set; }
        public virtual DbSet<pickers> pickers { get; set; }
        public virtual DbSet<empleados> empleados { get; set; }
        public virtual DbSet<kits> kits { get; set; }
        public virtual DbSet<kitskus> kitskus { get; set; }
        public virtual DbSet<wl_cajas> wl_cajas { get; set; }
        public virtual DbSet<skusbenavides> skusbenavides { get; set; }
        public virtual DbSet<skushomedelivery> skushomedelivery { get; set; }
        public virtual DbSet<hd_codigosqr> hd_codigosqr { get; set; }
        public virtual DbSet<hd_guias> hd_guias { get; set; }
        public virtual DbSet<hd_ordenes> hd_ordenes { get; set; }
        public virtual DbSet<hd_statusorden> hd_statusorden { get; set; }
        public virtual DbSet<hd_statusquickship> hd_statusquickship { get; set; }
        public virtual DbSet<hd_detordenesskus> hd_detordenesskus { get; set; }
    }
}
