//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFAWaldos.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class wl_cajas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public wl_cajas()
        {
            this.wl_detcajassku = new HashSet<wl_detcajassku>();
            this.wl_detenvios = new HashSet<wl_detenvios>();
        }
    
        public int id { get; set; }
        public string Codigo { get; set; }
        public int wl_statuscajas_Id { get; set; }
        public Nullable<int> Pickers_Id { get; set; }
        public Nullable<int> Auditores_Id { get; set; }
        public Nullable<int> Paquetes { get; set; }
    
        public virtual auditores auditores { get; set; }
        public virtual pickers pickers { get; set; }
        public virtual wl_statuscajas wl_statuscajas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wl_detcajassku> wl_detcajassku { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wl_detenvios> wl_detenvios { get; set; }
    }
}
