//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFAWaldos.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class wl_detenvios
    {
        public int id { get; set; }
        public int wl_tiendas_Id { get; set; }
        public int wl_cajas_Id { get; set; }
        public int wl_guias_Id { get; set; }
        public int wl_waldos_Id { get; set; }
    
        public virtual wl_guias wl_guias { get; set; }
        public virtual wl_tiendas wl_tiendas { get; set; }
        public virtual wl_waldos wl_waldos { get; set; }
        public virtual wl_cajas wl_cajas { get; set; }
    }
}
